# Generated by Django 2.2.1 on 2019-05-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsquad',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
